import type { AssetRegistry } from "./types.js";

export const defaultAssetRegistry: AssetRegistry = {
  assets: {
    "local.qwen35": {
      class: "owned_capacity",
      substrate: "openai-compatible.local",
      model: "qwen3.6-35b-a3b-q4",
      contextWindow: 128000,
      observedTps: 31,
      inputCostPerMTok: 0,
      cachedInputCostPerMTok: 0,
      outputCostPerMTok: 0,
      privacy: "local",
      qualityTier: "mid",
      tags: ["coding", "debug", "cheap-broad-scan"],
    },
    "remote.cheap": {
      class: "metered_api",
      substrate: "mock",
      model: "cheap-remote",
      contextWindow: 128000,
      observedTps: 80,
      inputCostPerMTok: 0.2,
      cachedInputCostPerMTok: 0.02,
      outputCostPerMTok: 1.0,
      privacy: "remote",
      qualityTier: "cheap",
    },
    "remote.premium": {
      class: "metered_api",
      substrate: "mock",
      model: "premium-frontier",
      contextWindow: 256000,
      observedTps: 45,
      inputCostPerMTok: 5.0,
      cachedInputCostPerMTok: 0.5,
      outputCostPerMTok: 30.0,
      privacy: "remote",
      qualityTier: "frontier",
    },
    "subscription.smart": {
      class: "subscription_quota",
      substrate: "mock",
      model: "subscription-smart",
      contextWindow: 128000,
      observedTps: 60,
      quotaRemaining: 20,
      quotaResetHours: 8,
      privacy: "remote",
      qualityTier: "smart",
    },
  },
};
